spring:
  datasource:
    username: sa
    password: AdminNeta2018*
    url: jdbc:sqlserver://192.168.100.142:1433;databaseName=neta_db
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
neta:
  application:
    name: app-local
    version: 99.99